name: camicro
channels:
  - pytorch
  - nvidia
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.11.17=py39h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cuda=11.6.1=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=12.4.127=0
  - cuda-libraries=11.6.1=0
  - cuda-libraries-dev=11.6.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.4.127=0
  - cuda-nsight-compute=12.4.1=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=12.4.127=0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=12.4.127=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=12.4.127=0
  - cuda-runtime=11.6.1=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=12.4.127=0
  - cuda-toolkit=11.6.1=0
  - cuda-tools=11.6.1=0
  - cuda-visual-tools=11.6.1=0
  - decorator=5.1.1=pyhd3eb1b0_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gds-tools=1.9.1.3=0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py39h06a4308_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.6.0=py39h06a4308_0
  - jupyter_core=5.5.0=py39h06a4308_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.9.2.110=h5e84587_0
  - libcublas-dev=11.9.2.110=h5c901ab_0
  - libcufft=10.7.1.112=hf425ae0_0
  - libcufft-dev=10.7.1.112=ha5ce4c0_0
  - libcufile=1.9.1.3=0
  - libcufile-dev=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurand-dev=10.3.5.147=0
  - libcusolver=11.3.4.124=h33c3c4e_0
  - libcusparse=11.7.2.124=h7538f96_0
  - libcusparse-dev=11.7.2.124=hbbe9722_0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.6.3.124=hd2722f0_0
  - libnpp-dev=11.6.3.124=h3c42840_0
  - libnvjpeg=11.6.2.124=hd473ad6_0
  - libnvjpeg-dev=11.6.2.124=hb5906b9_0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - nsight-compute=2024.1.1.4=0
  - numpy=1.26.4=py39h5f9d8c6_0
  - numpy-base=1.26.4=py39hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_2
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.3.0=py39h5eee18b_0
  - pip=24.0=py39h06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - python=3.9.19=h955ad1f_1
  - pytorch=1.13.0=py3.9_cuda11.6_cudnn8.3.2_0
  - pytorch-cuda=11.6=h867d48c_1
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py39h06a4308_1
  - setuptools=69.5.1=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=0.13.0=py39_cu116
  - torchvision=0.14.0=py39_cu116
  - typing_extensions=4.11.0=py39h06a4308_0
  - urllib3=2.1.0=py39h06a4308_0
  - wheel=0.43.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - accelerate==0.30.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - altair==5.3.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.3.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asciitree==0.3.3
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - blinker==1.8.2
      - cachetools==5.3.3
      - cffi==1.16.0
      - click==8.1.7
      - comm==0.2.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - datasets==2.19.1
      - debugpy==1.8.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - evaluate==0.4.2
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fasteners==0.19
      - fastjsonschema==2.19.1
      - filelock==3.14.0
      - fonttools==4.51.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.23.0
      - hydra-core==1.3.2
      - imagecodecs==2024.6.1
      - imageio==2.34.1
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - ipykernel==6.29.4
      - ipython==8.18.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - json5==0.9.25
      - jsonpointer==2.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.0.2
      - multidict==6.0.5
      - multiprocess==0.70.16
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - notebook==7.2.0
      - notebook-shim==0.2.4
      - numcodecs==0.12.1
      - omegaconf==2.3.0
      - opencv-python-headless==4.10.0.84
      - overrides==7.7.0
      - packaging==24.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.2.2
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - protobuf==4.25.3
      - psutil==5.9.8
      - pyarrow==16.0.0
      - pyarrow-hotfix==0.6
      - pycparser==2.22
      - pydeck==0.9.1
      - pygments==2.18.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - referencing==0.35.1
      - regex==2024.5.10
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.18.1
      - safetensors==0.4.3
      - scikit-image==0.22.0
      - scipy==1.13.1
      - send2trash==1.8.3
      - shapely==2.0.4
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - stack-data==0.6.3
      - stqdm==0.0.5
      - streamlit==1.35.0
      - tabulate==0.9.0
      - tenacity==8.3.0
      - terminado==0.18.1
      - tifffile==2024.5.22
      - tiffslide==2.4.0
      - tinycss2==1.3.0
      - tokenizers==0.19.1
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.12.1
      - torch-summary==1.4.5
      - torchinfo==1.8.0
      - tornado==6.4
      - tqdm==4.66.4
      - traitlets==5.14.3
      - transformers==4.40.2
      - types-python-dateutil==2.9.0.20240316
      - tzdata==2024.1
      - uri-template==1.3.0
      - watchdog==4.0.1
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - wsinfer==0.6.1
      - wsinfer-zoo==0.6.2
      - xxhash==3.4.1
      - yarl==1.9.4
      - zarr==2.18.2
      - zipp==3.18.2

